- ros_topic_name: "/clock"
  gz_topic_name: "/world/walls/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: "GZ_TO_ROS"
- ros_topic_name: "/scan"
  gz_topic_name: "/world/walls/model/x500_lidar_0/link/link/sensor/lidar_2d_v2/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  subscriber_queue: 50
  publisher_queue: 50
  lazy: false
  direction: "GZ_TO_ROS"
- ros_topic_name: "/points"
  gz_topic_name: "/world/walls/model/x500_lidar_0/link/link/sensor/lidar_2d_v2/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 50
  publisher_queue: 50
  lazy: false
  direction: "GZ_TO_ROS"
